### ISSUE TITLE
Update the whole basics documentation of front-end

### ISSUE THREAD

**Issue by ghost** [harsh-2711/getting-started#13]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

**Other information:**

**Comment by harsh-2711** [comment]
@waterupto Please add some description to this issue so that I can know what you want to add.

**Comment by ghost** [comment]
Update the basics of React, Vue and Angular.

**Comment by harsh-2711** [comment]
@waterupto Please open a separate issue for each one of them and mention what are you doing in the issue description.

**Comment by harsh-2711** [comment]
@waterupto I'm closing this issue for now. You can open new issues for your feature requests.
