### ISSUE TITLE
Add Bootstrap Template and Documentation

### ISSUE THREAD

**Issue by ghost** [harsh-2711/getting-started#18]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

There is no template starter and documentation mentioned in the repository.
**Expected behavior:**

A template starter and a quick tutorial would be provided for the users.
**Other information:**

**Comment by ghost** [comment]
Due to some problems, I had to remove my previous GitHub account. From now on, I will be contributing through this. Please assign this issue to me.

**Comment by harsh-2711** [comment]
Noted 👍
