### ISSUE TITLE
Add Flutter Starter Template

### ISSUE THREAD

**Issue by ghost** [harsh-2711/getting-started#23]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

There is no starter template for the Flutter.

**Expected behavior:**

Will provide a quick tutorial as well as a starter template for Flutter.

**Other information:**

**Comment by harsh-2711** [comment]
@waterupto I think @maruf212000 is also working on the same issue #19. Can you please check with him first before proceeding with this issue?
