### ISSUE TITLE
Refactor CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by atarax665** [harsh-2711/getting-started#4]
**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request

**Current behavior:**

Encountered few typos and grammatical errors in the doc.
Ex - 
* we as contributors and maintainers pledge to **making** participation in our project and our community a harassment-free experience for everyone,
* Enforcement
   Instances of abusive, harassing*,* or otherwise unacceptable behavior may be reported by contacting the project team at***  .

**Expected behavior:**

* we as contributors and maintainers pledge to *make* participation in our project
*  Instances of abusive, harassing or otherwise unacceptable behavior may be reported by contacting the project team at .... (Need to add a link here where people can complain) 

**Other information:**

*None*

**Comment by harsh-2711** [comment]
I'll assign this issue to you.

**Comment by atarax665** [comment]
@harsh-2711 Can you let me know the email id that could be used to report complaints ?

**Comment by harsh-2711** [comment]
For now, we can use this email ID - harshaudi27@gmail.com
