### ISSUE TITLE
Add Django starter template

### ISSUE THREAD

**Issue by atarax665** [harsh-2711/getting-started#8]
**I'm submitting a ...** 

- [ ] bug report
- [X] feature request

**Current behavior:**

There is no template available for Django.

**Expected behavior:**

A basic Django template to help developers to get started with their projects ASAP. The template will also have a documentation to help beginners to setup their Django development environment.

**Other information:**

**Comment by harsh-2711** [comment]
@atarax665 I'm assigning this issue to you. But please note that there will be two `README.md` files, one in your template folder in which you will specify steps to set up or say start your template and one in the outer level i.e. in the Django folder which will mention your template in it along with some getting started links to tutorials or medium articles.

**Comment by atarax665** [comment]
> @atarax665 I'm assigning this issue to you. But please note that there will be two `README.md` files, one in your template folder in which you will specify steps to set up or say start your template and one in the outer level i.e. in the Django folder which will mention your template in it along with some getting started links to tutorials or medium articles.

Okay, I will do as suggested.
